.TH "AUDISPD" "8" "Jun 2007" "Red Hat" "System Administration Utilities"
.SH NAME
audispd \- The Linux Audit Dispatcher daemon

.SH SYNOPSIS
.B audispd

.SH DESCRIPTION
\fBaudispd\fP is one userspace component of the Linux Auditing System. It's responsible for dispatching audit records to the disk.
.P
The dispatcher is a program that is started by the audit daemon when it starts up.
It will pass a copy of all audit events to that application's stdin.

.SH SIGNALS
.TP
SIGTERM, SIGCHLD
terminates the daemon.
.TP
SIGHUP
is ignored.

.SH "SEE ALSO"
.BR auditd (8).

.SH AUTHOR
Steve Grubb
