.TH "AUPARSE_NEXT_RECORD" "3" "Feb 2007" "Red Hat" "Linux Audit API"
.SH NAME
auparse_next_record \- move record cursor
.SH "SYNOPSIS"
.B #include <auparse.h>
.sp
int auparse_next_record(auparse_state_t *au);

.SH "DESCRIPTION"
auparse_next_record will move the internal library cursors to point to the next record of the current event.

.SH "RETURN VALUE"

Returns -1 if an error occurs, 0 if no more records in current event, or 1 for success.

.SH "SEE ALSO"

.BR auparse_next_event (3).

.SH AUTHOR
Steve Grubb
